
CREATE TABLE formularios(

Nome VARCHAR(50),
Email VARCHAR(50),
IT VARCHAR(50),
FONE1 VARCHAR(50),
FONE2 VARCHAR(50),
Motivo VARCHAR(200),
ID INT PRIMARY KEY AUTO_INCREMENT
);

SELECT * FROM formularios;

DROP TABLE formularios;